# Generated by Django 4.2.16 on 2024-09-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default=0)),
                ('humidty', models.IntegerField(default=0)),
                ('hasWater', models.BooleanField(default=True)),
                ('date', models.DateTimeField(verbose_name='Entry date')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatusApp.user')),
            ],
        ),
    ]
