# Generated by Django 4.2.16 on 2024-09-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='humidty',
            new_name='humidity',
        ),
    ]
