# Generated by Django 4.2.16 on 2024-09-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0002_rename_humidty_entry_humidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='username',
        ),
        migrations.AddField(
            model_name='entry',
            name='device_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
