# Generated by Django 4.2.16 on 2024-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0004_alter_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='lightAmount',
            field=models.IntegerField(default=0),
        ),
    ]
